export { default as Hero } from './Hero'
export { default as Trusted } from './Trusted'
export { default as Features } from './Features'
export { default as Showcase } from './Showcase'
export { default as Metrics } from './Metrics'
export { default as Process } from './Process'
export { default as Testimonials } from './Testimonials'
export { default as Pricing } from './Pricing'
export { default as FAQ } from './FAQ'
export { default as CTA } from './CTA'

